id: alien4cloud-marathon-plugin
name: POC marathon plugin for alien
version: ${project.version}
description: >
  Plugin that contains a paas provider capable of deploying application onto marathon.
configuration_class: alien4cloud.plugin.marathon.PluginConfiguration
component_descriptors:
  - bean_name: marathon-orchestrator-factory
    name: Marathon Orchestrator Factory
    description: >
      Orchestrator Factory that instanciate the marathon orchestrator.
#  - bean_name: docker-image-resolver
#    name: Docker Image Resolver